extends: site.yaml

mode: production
media_url: /dbuscombe/media
base_url: /dbuscombe
deploy_root: deploy_production

publisher:
    ssh:
        type: hyde.ext.publishers.ssh.SSH
        username: dbuscombe
        server: #jakevdp.ovid.u.washington.edu
        target: #/rc00/d68/jakevdp/public_html
